version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/car_db
    depends_on:
      - mongo
      - ai

  ai:
    build: ./ai-service
    ports:
      - "8000:8000"

  mongo:
    image: mongo:6
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
